feat: add CI apptainer building stage, improve test speed, fix minor CI bugs, add CI secrets, bump environments, add testmon & xdist pytest plugins for speeding up tests

diff --git a/datahub/Makefile b/datahub/Makefile
--- a/datahub/Makefile
+++ b/datahub/Makefile
@@ -10,6 +10,8 @@ PROJECT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
 # Set conda/mamba binary, mamba if available, conda otherwise
 CONDA_BINARY := $(shell command -v mamba || command -v conda)
 
+APPTAINER_BINARY := $(shell command -v apptainer || command -v singularity)
+
 #################################################################################
 # COMMANDS                                                                      #
 #################################################################################
@@ -40,38 +42,66 @@ _token_access_error:
 	echo "===============================================================================";
 	exit 1;
 
-## Create a new conda environment and install datahub
-env:
-	@echo "Creating datahub conda environment: `datahub`"
-	# Check if the GITLAB_USER and GITLAB_TOKEN are set
-	if [ -z "$(GITLAB_USER)" ] || [ -z "$(GITLAB_TOKEN)" ]; then \
+_check_conda:
+	@echo "... checking if conda/mamba is installed"
+	@command -v $(CONDA_BINARY) >/dev/null 2>&1 || { \
+		echo "Error: Conda/mamba is not installed or not found in PATH" >&2; \
+		exit 1; \
+	}
+	@echo "... found conda executable: $(CONDA_BINARY)"
+
+_check_tokens:
+	@echo "... checking if GITLAB_USER and GITLAB_TOKEN are set"
+	@if [ -z "$(GITLAB_USER)" ] || [ -z "$(GITLAB_TOKEN)" ]; then \
 		$(MAKE) _token_access_error; \
 	fi
-	$(CONDA_BINARY) env create -n datahub --file environment.yaml
-	conda init
-	conda activate datahub
-	pip install -e ".[dev]"
+	@echo "... found GITLAB_USER ($(GITLAB_USER)) and GITLAB_TOKEN."
+
+_check_apptainer:
+	@echo "... checking if apptainer is installed"
+	@command -v $(APPTAINER_BINARY) >/dev/null 2>&1 || { \
+		echo "Error: Apptainer is not installed or not found in PATH" >&2; \
+		exit 1; \
+	}
+	@echo "... found apptainer executable: $(APPTAINER_BINARY)"
+
+## Create a new conda environment and install datahub
+env:
+	@echo "Creating datahub conda environment: datahub"
+
+	@$(MAKE) --no-print-directory _check_tokens
+	@$(MAKE) --no-print-directory _check_conda
+
+	@$(CONDA_BINARY) env create -n datahub --file environment.yaml
+	@conda init
+	@conda activate datahub
+	@pip install -e ".[dev]"
 
 ## Install datahub locally into the current environment
 install:
 	@echo "Installing datahub"
-	# Check if the GITLAB_USER and GITLAB_TOKEN are set
-	if [ -z "$(GITLAB_USER)" ] || [ -z "$(GITLAB_TOKEN)" ]; then \
-		$(MAKE) _token_access_error; \
-	fi
-	# Install the conda requirements in the current activated environment
+
+	@$(MAKE) --no-print-directory _check_tokens
+	@$(MAKE) --no-print-directory _check_conda
+
+	@echo "Installing the conda requirements in the current activated environment"
 	$(CONDA_BINARY) env update --file environment.yaml
-	# Install the pip requirements in the current activated environment
+
+	@echo "Installing the pip requirements in the current activated environment"
 	pip install -e ".[dev]"
 
 ## Build the apptainer image
 apptainer:
-	# Check if the GITLAB_USER and GITLAB_TOKEN are set
-	if [ -z "$(GITLAB_USER)" ] || [ -z "$(GITLAB_TOKEN)" ]; then \
-		$(MAKE) _token_access_error; \
-	fi
-	$(eval DATE := $(shell date +%Y%m%d))
-	apptainer build --bind $(PWD):/datahub_host datahub_$(DATE).sif apptainer.spec
+	@echo "Building apptainer image"
+
+	@$(MAKE) --no-print-directory _check_apptainer
+	@$(MAKE) --no-print-directory _check_tokens
+
+	$(eval DATE := $(shell date +%Y-%m-%d))
+	$(eval IMAGE_NAME := datahub_$(DATE).sif)
+
+	@echo "Building apptainer image $(IMAGE_NAME)"
+	$(APPTAINER_BINARY) build --bind $(PWD):/datahub_host --bind /projects:/projects --bind /net/databases:/databases --bind /squash:/squash datahub_$(DATE).sif apptainer.spec
 
 ## Run pytest and generate coverage report
 test:
